services:
  web:
    build: .
    container_name: hunter_web
    volumes:
      - ./html:/var/www/html
    ports:
      - '80:80'
    links:
      - 'db:database'
  
  db: 
    image: 'mysql:latest'
    container_name: hunter_bdat
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: series
    ports:
      - '3306:3306'
  
  # PHPMYADMIN
  phpmyadmin:
    image: 'phpmyadmin:latest'
    container_name: hunter_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
    ports:
      - '8000:80'